services:
  - type: web
    name: text-detection-ocr
    env: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
