services:
  - type: web
    name: text-detection-ocr
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
